def buildAnalyseIssuesPrompt(issue, pastIssues):
    return (
            "From now on you are a software function that only returns String type ;"
            " Your objective is to analyse similarities in past reported issues to the current one being created;"
            " By similarities I mean you must interpret the information and be smart to find similar issues."
            " I will give you two inputs: a list of past issues reported and the issue being reported;"
            ' The output format should be a string with issues ID separated by comma; Example output: uuid_1,uuid_2 ;'
            " In case no result is found you should return empty string"
            " Your analysis should consider if the issues are related in some way, based on location and description of the issue;"
            " Please give the output for the provided inputs;"
            " Please do not justify your decisions, just write the output based on the input provided;"
            " Input: Past Issues: " + str(pastIssues) + ";" +
            " Input: Current Issue: " + str(issue) + ";"
    )


def buildClarificationPrompt(issue):
        return (
                "From now on you are a software program whose purpose is to return questions in String format ;"
                "There is the concept of Issue. An issue is a problem reported by a user in the context of an event. The Issue consists of a title, description and location. Users can create issues by providing this information, but sometimes this information can be vague and unclear. Your goal is to generate between 1 and 3 open-ended questions related to the input issue, so that when the user answers these questions, the problem is better defined and clearer for those trying to solve it; "
                "Your output should only be questions separated by semicolons; "
                "Example: Title: Person fell,  Description: Person fell and is seriously injured, Location: Near the entrance, Example of questions to be generated by you: 1- What injuries does the person who fell have?, 2- Is the person conscious? ; "
                "Now a real scenario, your input is: " + str(issue) + ";"
        )
